import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

const Home = (): JSX.Element => {
  return (
    <div>
      <Head>
        <title>Kinder Park Vila-real</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
        <nav>
          <div className="relative w-28 sm:w-44 flex flex-col mx-auto">
            <Link href="/">
              <a className="flex flex-grow">
                <Image
                  src="/images/logo.png"
                  alt=""
                  priority
                  width={300}
                  height={129}
                />
              </a>
            </Link>
          </div>
          <div className="h-10 flex flex-col bg-red-600">
            <ul className="flex flex-grow justify-evenly items-center text-gray-100 text-xs sm:text-sm md:text-base">
              <li>sobre nosotros</li>
              <li>servicios</li>
              <li>centro</li>
              <li>noticias</li>
              <li>contacto</li>
              <li>a</li>
            </ul>
          </div>
        </nav>
      </header>
      <main>
        <h1 className="font-brand">Kinder Park</h1>
      </main>
    </div>
  )
}

export default Home
