import Head from 'next/head'

export default function Home(): JSX.Element {
  return (
    <div>
      <Head>
        <title>Kinder Park - Inicio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1 className="font-brand">Kinder Park</h1>
      </main>
    </div>
  )
}
